// REACT
import React from 'react'
import PropTypes from 'prop-types'

// CARBON COMPONENTS
import { TextArea, Tooltip} from 'carbon-components-react'

// REACT-GRID-SYSTEM
import { Container, Row } from 'react-grid-system'
import Col from '../../Column' // CUSTOM COLUMN -> OPTIMIZED FOR SERVERS SIDE RENDERING

const AssetPublisher = (props) => {
  return (
    <Row className='' style={{marginTop: 20}}>
      <Col md={2} offset={{md: 1}}>
        <Tooltip triggerText="Publisher:">
          <p>
            This is autogenerated through your login to the system.
          </p>
        </Tooltip>
      </Col>
      <Col md={3}>
        <p>TODO: Publisher Name</p>
      </Col>
    </Row>
  )
}

export default AssetPublisher